# Register Users:
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Niko Bellic",
    "email": "Niko@email.com",
    "password": "niko1234"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Ignacio Varga",
    "email": "nacho@email.com",
    "password": "nacho5678"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Antonio Montana",
    "email": "tony@email.com",
    "password": "tony010101"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Sarah Connor",
    "email": "sarah@email.com",
    "password": "sarah050505"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Brienne de Tarth",
    "email": "brienne@email.com",
    "password": "brienne12345"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Obito Uchiha",
    "email": "obito@email.com",
    "password": "obito12345"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Shikamaru Nara",
    "email": "shikamaru@email.com",
    "password": "shikamaru12345"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Mike Ehrmantraut",
    "email": "mikeu@email.com",
    "password": "mike12345"
}

# Register Posts:
###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "https://i.pinimg.com/originals/c6/6a/43/c66a436cf9a9d8fb903b9d71bc4112fe.jpg",
    "description": "Vamos jogar boliche?",
    "type": "event",
    "authorId": "c8a32547-6d51-4cd7-b5b5-d92722b5d21d"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "https://canalcienciascriminais.com.br/wp-content/uploads/2017/03/Scarface.jpg",
    "description": "say hello to my little friend",
    "type": "normal",
    "authorId": "fe4cb2a3-d537-4a94-9fba-93a1f3e10f8b"
}

# Get Posts by id:
###
GET http://localhost:3003/post/89412971-4b94-46bd-84a9-35b2b882bbd9
Content-Type: application/json

###
GET http://localhost:3003/post/4e1528d7-0021-42ff-bc4c-506a9a9cb3a5
Content-Type: application/json
